output_root: 'aachen/PoSFeat_mytrain'
postfix: 'PoSFeat_mytrain'
load_path: './ckpts/keypoint/005'

loss_distance: 'cos'
output_desc: True
output_img: False

model: 'PoSFeat'
model_config: 
    backbone: None
    backbone_config: None
    localheader: None
    localheader_config: None

data: 'Aachen_Day_Night' 
data_config_extract:
    data_path: '/home/kunbpc/data/kunb/aachen/aachen/images/images_upright'
    prune_kp: False
    batch_size: 1
    workers: 4

local_thr: 0.99 # only used in save image

use_sift: False
detector: 'generate_kpts_single'
detector_config:
    num_pts: 20480
    stable: True
    use_nms: True # softnms, True, False
    nms_radius: 3
    thr: 0.5 # False or a float
    thr_mod: abs # max mean abs
detector_config_query:
    num_pts: 20480
    stable: True
    use_nms: True # softnms, True, False
    nms_radius: 3
    thr: 0.5 # False or a float
    thr_mod: abs # max mean abs